version: '3'

volumes:
  parzellenwetter_postgres_data:
    driver: local

services:
  postgres:
    container_name: parzellenwetter-postgres_container
    image: postgres:16.3-alpine
    volumes:
      - parzellenwetter_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: parzellenwetter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
  parzellenwetter_app:
    container_name: parzellenwetter_app
    build: .
    image: kairenken/parzellenwetter:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://parzellenwetter-postgres_container:5432/parzellenwetter_db
    ports:
      - "8080:8080"